name: diffusion
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - accelerate=0.24.1
  - anyio=3.7.1
  - arrow=1.3.0
  - attrs=23.1.0
  - backoff=2.2.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - blas=1.0
  - blessed=1.19.1
  - boto3=1.29.0
  - botocore=1.32.1
  - bottleneck=1.3.5
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cachecontrol=0.12.11
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cleo=2.0.1
  - click=8.1.3
  - colorama=0.4.6
  - crashtest=0.4.1
  - croniter=1.4.1
  - cryptography=41.0.3
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - dateutils=0.6.12
  - dbus=1.13.6
  - deepdiff=5.8.1
  - distlib=0.3.7
  - dulwich=0.21.3
  - einops=0.7.0
  - exceptiongroup=1.1.3
  - expat=2.2.10
  - fastapi=0.104.1
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.10.4
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - h11=0.14.0
  - html5lib=1.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.1
  - inquirer=3.1.3
  - intel-openmp=2023.1.0
  - itsdangerous=2.1.2
  - jaraco.classes=3.3.0
  - jeepney=0.8.0
  - jinja2=3.1.2
  - jmespath=1.0.1
  - jpeg=9e
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.11.1
  - keyring=23.13.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.8.0.34
  - libcurand=10.3.4.52
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lightning=2.1.1
  - lightning-cloud=0.5.50
  - lightning-utilities=0.9.0
  - llvm-openmp=14.0.6
  - lockfile=0.12.2
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.1
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - more-itertools=10.1.0
  - mpmath=1.3.0
  - msgpack-python=1.0.3
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=2.8.8
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numexpr=2.8.7
  - numpy-base=1.26.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.12
  - ordered-set=4.1.0
  - packaging=23.2
  - pandas=2.1.1
  - pcre=8.45
  - pexpect=4.8.0
  - pillow=10.0.1
  - pip=23.3
  - pkginfo=1.9.6
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - poetry=1.4.0
  - poetry-core=1.5.1
  - poetry-plugin-export=1.3.0
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pydantic=1.10.12
  - pygments=2.16.1
  - pyjwt=2.8.0
  - pyopenssl=23.2.0
  - pyproject_hooks=1.0.0
  - pysocks=1.7.1
  - python=3.9.18
  - python-build=0.10.0
  - python-dateutil=2.8.2
  - python-editor=1.0.4
  - python-installer=0.6.0
  - python-multipart=0.0.6
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytorch=2.1.0
  - pytorch-cuda=11.8
  - pytorch-lightning=2.1.0
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyyaml=6.0
  - rapidfuzz=2.13.7
  - readchar=4.0.5
  - readline=8.2
  - referencing=0.31.0
  - requests=2.31.0
  - requests-toolbelt=0.10.1
  - rich=13.6.0
  - rpds-py=0.10.6
  - s3transfer=0.7.0
  - scikit-learn=1.0.2
  - scipy=1.8.1
  - secretstorage=3.3.3
  - setuptools=68.0.0
  - shellingham=1.5.4
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - starlette=0.27.0
  - starsessions=1.3.0
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - tomli=2.0.1
  - tomlkit=0.12.3
  - torchaudio=2.1.0
  - torchmetrics=1.2.0
  - torchtriton=2.1.0
  - torchvision=0.16.0
  - tqdm=4.66.1
  - traitlets=5.13.0
  - trove-classifiers=2023.11.14
  - types-python-dateutil=2.8.19.14
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - urllib3=1.26.18
  - uvicorn=0.24.0
  - virtualenv=20.17.1
  - wcwidth=0.2.10
  - webencodings=0.5.1
  - websocket-client=1.6.4
  - websockets=10.4
  - wheel=0.41.2
  - xz=5.4.2
  - yaml=0.2.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - beartype==0.16.4+computecanada
    - ema-pytorch==0.3.0+computecanada
    - fsspec==2023.10.0+computecanada
    - huggingface-hub==0.19.1
    - joblib==1.3.2+computecanada
    - threadpoolctl==3.2.0+computecanada
